version: "3.9"
services:

  haproxy:
    container_name: haproxy
    ports:
      - 80:80
    image: haproxytech/haproxy-alpine
    volumes:
      - ./haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg
      - ./haproxy/hosts.map:/etc/haproxy/hosts.map
      - ./haproxy/blacklist.acl:/etc/haproxy/blacklist.acl
      - ./haproxy/blocked.map:/etc/haproxy/blocked.map
      - ./haproxy/whitelist.map:/etc/haproxy/whitelist.map

  nginx-v1:
    container_name: nginx-v1
    ports:
      - 81:81
    image: "quay.io/shardul/nginx:v1"
    volumes:
      - ./nginx/default-v1.conf:/etc/nginx/conf.d/default.conf

  nginx-v2:
    container_name: nginx-v2
    ports:
      - 82:82
    image: "quay.io/shardul/nginx:v2"
    volumes:
      - ./nginx/default-v2.conf:/etc/nginx/conf.d/default.conf

