version: "3.9"
services:

  haproxy:
    container_name: haproxy
    ports:
      - 80:80
    image: haproxytech/haproxy-alpine
    volumes:
      - ./haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg
      - ./haproxy/hosts.map:/etc/haproxy/hosts.map
      - ./haproxy/blacklist.acl:/etc/haproxy/blacklist.acl
      - ./haproxy/blocked.map:/etc/haproxy/blocked.map
      - ./haproxy/whitelist.map:/etc/haproxy/whitelist.map

  nginx:
    container_name: nginx
    ports:
      - 81:80
    image: "nginx:latest"
    volumes:
      - ./nginx:/usr/share/nginx/html

